apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app: kubeauth
---
apiVersion: v1
kind: Secret
metadata:
  name: kubeauth-controller-tls-secret
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: |
    {{ .Values.controller.tls.cert }}
  tls.key: |
    {{ .Values.controller.tls.key }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeauth-controller
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kubeauth-controller
  template:
    metadata:
      labels:
        component: kubeauth-controller
    spec:
      containers:
        - name: kubeauth-controller
          imagePullPolicy: IfNotPresent
          image: {{ .Values.controller.image }}
          volumeMounts:
          - name: kubeauth-controller-tls-secret
            mountPath: /run/secrets/tls
            readOnly: true
      volumes:
      - name: kubeauth-controller-tls-secret
        secret:
          secretName: kubeauth-controller-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: kubeauth-controller-service
  namespace: {{ .Values.namespace }}
  labels:
    component: kubeauth-controller-service
spec:
  ports:
    - port: {{ .Values.controller.ports.service }}
      targetPort: 8443
  selector:
    component: kubeauth-controller
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kubeauth-webhook-admission-conf
  namespace: {{ .Values.namespace }}
webhooks:
  - name: kubeauth-controller-service.{{ .Values.namespace }}.svc
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: kubeauth-controller-service
        namespace: kubeauth-system
        path: "/mutate"
        port: {{ .Values.controller.ports.service }}
      caBundle: "{{ .Values.controller.tls.cert }}"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]

